env:
  global:
  - secure: XXvdPTS+E85muHfM4UuvYYkTSiWd/WkkXAQy0mq99n1l5xBFOqSiTfVMPO/NEySC3GNlvwY5/kb4dJ1t1H1Ay+vQNa+oS73HMShS5eH+JSegV3wH+2YtnAkuZsuV/1GacYe3gliwCego6A3Hh5cBGhE7OVgujDSQYKucb+xwzE8PlNf74WnKG88hSbJWnhn/CJo4W3SpqK3g9RXL1L9MCVtJgIYc5Lh5aQb3+Y9Z7KZhp+uoH8gaJO7favtBR36ixq+rAZiJcxSmv7G0l6e/TF3MzYEgsgTbZvpQKodVYVuubbyx2FUyNUEVCck1pXtpB9vqUixE0W3NzY7RX27tg/9oL52dHTMmOgfJdLNkr8SClpzNB+BPKvCzdhs8QgrUCHt2/2rxz1BNzrGJ9FJXgfS+yju6bgkZiJQG7LM5SCbrkSgkZtroAkVaRHvqwlcrTK7r5k+IACyUNBii0nDgwgO7Vt0UgIJ/RjXsK1JGqMy69YCuxpQH7ZnGfhJ73echsbTiHtVQh60skz4ae3mz/BcEsqE446Z0gq9YBxoYln7SwDT1oeG0wv3tZAbjwI43BPBqGhQXiF1J2jv6vuLrkVji1RwWRh38Cf0abBrg+RXRkQ/fU8sa4q6PN8hCfMUHyccKg/TUbJpDau+GCq1hCFL6LZi267Lrq/PjaLBF8W8=
  - secure: lPsn9cl6lAX9qkhDBsQ/A4tVixc8p/IhcQQU0aNwD/5VJWlkcyTI1xbV1+P07m40NYaW5FvVXHApOlYHh/pDPH8dsuQG1oPNFvut56u2Qbe1aY/tJuqtMNZuhVfOj6caVcl+hFTT8ExhE6DRwpGJjbB6GafXQ5BiWUbNc0oiG8Yqk0ZES7MGovdG4C1qU8sZB3L7e0IUV4WYHJ2ylNNyTNsD0/eoT9lV+YheXaetnrjx35HLH1owUIKz3Q2J1BIhK8JDYuHiXnSJ+ACzlwfyT9s3KOKQJZqZKkCMdR0jzJOvX67nJHc/IE3oLouzsVGwnRvIYrpLb6jdE0Mgd3kWkSEsO6fwH9xxQMNCzfgq8YO/JGDe1kZU3uyf+aBZu1SPFaCN7O6rSyHhk+q5oRQlcxjsT7gwLmFn+Zj9svHG4TrPx1Xw4wWvgk/KVxVsO/G7dgGh0sQ0lIlCwsa20ogKmVM4d0TTU9CuAN98qaAtXb15UmVw3em8jeartHhD1G7fbDGz6+yvGbYYOBMO4tUb5xC+wCu6T3RoL9ChGypJE8jkRESfLLYU5ydinhokMTMKWwlzsjwoDw+DG/IAV2AMf5rl92+6frfFN2dVor9XjM9hYJOOA9J/swlluMSA5NtUDMYHZR6INOyqEl0jIKWMsh/T9/bi2bfU5siswuvlyVM=

php:
  - 5.6
  - 7.0

addons:
  ssh_known_hosts: $DEPLOY_HOST 

before_install:
- openssl aes-256-cbc -K $encrypted_ac356ff71e5e_key -iv $encrypted_ac356ff71e5e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- ls -la
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/web $DEPLOY_USER@$DEPLOY_HOST:staging
  on:
    branch: master
